import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        'node_modules/preline/dist/*.js',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
                'label-md': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'body-md': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                'headline-md': ['Libre Caslon Text', ...defaultTheme.fontFamily.serif],
                'display-lg': ['Libre Caslon Text', ...defaultTheme.fontFamily.serif],
                'body-lg': ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
            },
            fontSize: {
                'display-lg': ['4rem', { lineHeight: '1.05', letterSpacing: '-0.02em' }],
                'display-lg-mobile': ['2.25rem', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
                'headline-lg': ['2.5rem', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
                'label-md': ['0.875rem', { lineHeight: '1.25' }],
                'body-md': ['1rem', { lineHeight: '1.75' }],
                'body-lg': ['1.125rem', { lineHeight: '1.75' }],
                caption: ['0.75rem', { lineHeight: '1rem' }],
            },
            colors: {
                'tertiary-fixed-dim': '#e9c267',
                'surface-bright': '#fcf9f2',
                tertiary: '#4c3800',
                'tertiary-container': '#684e00',
                'on-tertiary-container': '#e8c066',
                'surface-variant': '#e5e2db',
                'on-primary-fixed': '#00210f',
                'primary-fixed': '#b1f1c3',
                'on-tertiary': '#ffffff',
                'on-error-container': '#93000a',
                'on-error': '#ffffff',
                'on-tertiary-fixed-variant': '#5b4300',
                'inverse-on-surface': '#f3f0e9',
                'on-secondary-fixed-variant': '#344e02',
                background: '#fcf9f2',
                'tertiary-fixed': '#ffdf9b',
                'surface-container-low': '#f6f3ec',
                error: '#ba1a1a',
                'on-secondary': '#ffffff',
                'surface-container-high': '#ebe8e1',
                'surface-container': '#f0eee7',
                'inverse-surface': '#31312c',
                primary: '#004525',
                secondary: '#4a671b',
                'on-surface': '#1c1c18',
                'on-primary-fixed-variant': '#10512f',
                'on-primary': '#ffffff',
                'secondary-fixed-dim': '#b0d279',
                'on-tertiary-fixed': '#251a00',
                outline: '#707971',
                'surface-dim': '#dcdad3',
                'on-secondary-fixed': '#121f00',
                'error-container': '#ffdad6',
                'on-surface-variant': '#404942',
                'outline-variant': '#c0c9bf',
                'on-background': '#1c1c18',
                'inverse-primary': '#95d5a8',
                'on-primary-container': '#94d4a7',
                surface: '#fcf9f2',
                'surface-container-highest': '#e5e2db',
                'primary-container': '#1f5d3a',
                'on-secondary-container': '#506d21',
                'surface-tint': '#2d6a46',
                'surface-container-lowest': '#ffffff',
                'secondary-fixed': '#cbef92',
                'primary-fixed-dim': '#95d5a8',
                'secondary-container': '#cbef92',
            },
            spacing: {
                'margin-mobile': '16px',
                xs: '4px',
                sm: '12px',
                base: '8px',
                md: '24px',
                lg: '48px',
                xl: '80px',
                'margin-desktop': '40px',
                gutter: '24px',
            },
            maxWidth: {
                'container-max': '1280px',
            },
        },
    },

    plugins: [
        forms,
        require('preline/plugin'),
    ],
    darkMode: 'class',
};
